Fix bug due to langchain's package updates, pin versions to avoid.  Fixes ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context'